version: '3.9'
services:
  db:
    image: mongo:5.0
    ports:
      - '27017:27017'
  web:
    image: public.ecr.aws/ideacrew/ite-api:latest
    ports:
      - '3000:3000'
    depends_on:
      - db
